frontend/models/LoginForm.php
<?php
namespace frontend\models;

use app\App;
use app\base\Helper;
use app\base\Model;
use frontend\models\User;

/**
 * Class frontend\models\LoginForm
 *
 * @property string $username
 * @property string $password
 */
class LoginForm extends Model
{
    public string $username;
    public string $password;

    /**
     * @return bool
     */
    public function validate():bool
    {
        $this->username = Helper::cleanValue($this->username);
        if (!$this->username) {
            $this->setErrors('username', 'Required field «Username»');
        }

        $this->password = Helper::cleanValue($this->password);
        if (!$this->password) {
            $this->setErrors('password', 'Required field «Password»');
        }

        if (!$this->hasErrors()) {
            if ( !($model = User::findByUsername($this->username)) || ($model && !$model->validatePassword($this->password) ) ) {
                $this->setErrors('username', '«Username» is incorrect.');
                $this->setErrors('password', '«Password» is incorrect.');
            }
            elseif (!$model->status) {
                $this->setErrors('username', '«Username» has blocked.');
            }
        }

        return !$this->hasErrors();
    }

    /**
     * @return User
     */
    public function getUser():User
    {
        return User::findByUsername($this->username);
    }

    /**
     * @return bool
     */
    public function doLogin():bool
    {
        return App::$app->auth->login($this->getUser());
    }
}

frontend/controllers/AuthController.php
<?php
namespace frontend\controllers;

use app\App;
use app\web\Controller;
use app\base\Helper;
use frontend\models\LoginForm;
use frontend\models\RegistrationForm;

/**
 * Class frontend\controllers\AuthController
 */
class AuthController extends Controller
{
    /**
     * @return string
     * @throws \ReflectionException
     */
    public function actionLogin()
    {

        $action = Helper::getUrlFull('/'.App::getConfig('default')['authRoute']);

        $model = new LoginForm();

        if (App::$app->request->isAjax) {
            if ($model->load(App::$app->request->post)) {
                if ($model->validate()) {
                    if ($model->doLogin()) {
                        App::$app->session->setValue('alert', [
                            'type' => 'success',
                            'message' => 'You have successfully logged in!'
                        ]);

                        return $this->renderAjax(['success' => true, 'redirect' => Helper::getUrlFull('/')]);
                    }
                    else {
                        App::$app->session->setValue('alert', [
                            'type' => 'danger',
                            'message' => 'Something went wrong, please try later!'
                        ]);

                        return $this->renderAjax(['success' => false, 'redirect' => $action]);
                    }
                }
                else {
                    return $this->renderAjax(['success' => false, 'errors' => $model->getErrors()]);
                }
            }
        }

        return $this->render('auth/login', [
            'model' => $model,
            'action' => $action
        ]);
    }

    /**
     * @return string.
     */
    public function actionLogout()
    {
        App::$app->auth->logout();

        return $this->redirect('/');
    }

    /**
     * @return string.
     * @throws \ReflectionException
     */
    public function actionRegistration()
    {
        $action = Helper::getUrlFull('/'.'auth/registration');

        $model = new RegistrationForm();

        if (App::$app->request->isAjax) {
            if ($model->load(App::$app->request->post)) {
                if ($model->validate()) {
                    if ($model->doRegistration()) {
                        App::$app->session->setValue('alert', [
                            'type' => 'success',
                            'message' => 'You have successfully create!'
                        ]);

                        return $this->renderAjax(['success' => true, 'redirect' => Helper::getUrlFull('/')]);
                    }
                    else {
                        App::$app->session->setValue('alert', [
                            'type' => 'danger',
                            'message' => 'Something went wrong, please try later!'
                        ]);

                        return $this->renderAjax(['success' => false, 'redirect' => $action]);
                    }
                }
                else {
                    return $this->renderAjax(['success' => false, 'errors' => $model->getErrors()]);
                }
            }
        }

        return $this->render('auth/registration', [
            'model' => $model,
            'action' => $action
        ]);
    }
}

frontend/views/layouts/main.php
<?php
/* @var $content String */

use app\App;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $this->title?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link href="/assets/css/styles.css" rel="stylesheet" />
</head>
<body>
    <div class="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a href="/" class="navbar-brand">Todo List</a>
                <div>
                    <a href="/create" class="btn btn-primary">Create</a>
                    <? if (App::$app->isAuth()) { ?>
                        <a href="/auth/logout" class="btn btn-primary">Logout (<?= App::$app->auth->user->username ?>)</a>
                    <? } else { ?>
                        <a href="/auth/login" class="btn btn-primary">Login</a>
                    <? } ?>
                </div>
            </div>
        </nav>
    </div>
    <div class="container p-3">
        <?= $this->renderContent('site/_alert', [

        ]) ?>

        <?php echo $content ?>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="/assets/js/scripts.js"></script>
</body>
</html>